dist: trusty
sudo: false
notifications:
  email: false
language: node_js
node_js:
  - "8"
  - "6"
  - "4"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run test-system
jobs:
  include:
    - stage: npm release
      if: branch = master AND type != pull_request
      node_js: "8" # This *has* to be the "build leader"
      script: npx semantic-release
branches:
  only:
    - master
